from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from quant.domain.paper import (
    PaperObservation,
    PaperParticipant,
    PaperSession,
    PaperSnapshot,
)


class PaperRepository(Protocol):
    def add_session(self, session: PaperSession) -> None: ...
    def save_session(self, session: PaperSession) -> None: ...
    def get_session(self, session_id: UUID) -> PaperSession | None: ...
    def list_sessions(self) -> Sequence[PaperSession]: ...
    def add_participant(self, participant: PaperParticipant) -> None: ...
    def save_participant(self, participant: PaperParticipant) -> None: ...
    def get_participant(self, participant_id: UUID) -> PaperParticipant | None: ...
    def list_participants(self, session_id: UUID) -> Sequence[PaperParticipant]: ...
    def add_observation(self, observation: PaperObservation) -> None: ...
    def get_observation(
        self, session_id: UUID, timestamp: datetime
    ) -> PaperObservation | None: ...
    def list_observations(self, session_id: UUID) -> Sequence[PaperObservation]: ...
    def add_snapshot(self, snapshot: PaperSnapshot) -> None: ...
    def latest_snapshot(self, participant_id: UUID) -> PaperSnapshot | None: ...
    def list_snapshots(self, participant_id: UUID) -> Sequence[PaperSnapshot]: ...
