from collections.abc import Sequence
from typing import Protocol

from quant.domain.paper_broker import (
    AlpacaPaperAccount,
    AlpacaPaperFill,
    AlpacaPaperOrder,
    AlpacaPaperPosition,
    SubmitAlpacaPaperOrder,
)


class PaperBrokerPort(Protocol):
    def get_account(self) -> AlpacaPaperAccount: ...
    def submit_order(self, request: SubmitAlpacaPaperOrder) -> AlpacaPaperOrder: ...
    def list_orders(self, status: str = "open") -> Sequence[AlpacaPaperOrder]: ...
    def get_order(self, order_id: str) -> AlpacaPaperOrder: ...
    def list_positions(self) -> Sequence[AlpacaPaperPosition]: ...
    def get_position(self, symbol: str) -> AlpacaPaperPosition: ...
    def close_position(self, symbol: str) -> AlpacaPaperOrder: ...
    def list_fills(self) -> Sequence[AlpacaPaperFill]: ...
