from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from quant.domain import PaperPromotion


class PaperPromotionRepository(Protocol):
    def add(self, promotion: PaperPromotion) -> None: ...
    def save(self, promotion: PaperPromotion) -> None: ...
    def get(self, promotion_id: UUID) -> PaperPromotion | None: ...
    def get_for_lineage(
        self, run_id: UUID, strategy_version_id: UUID, gate_id: UUID
    ) -> PaperPromotion | None: ...
    def list_all(self) -> Sequence[PaperPromotion]: ...
