const api = "/api/v1";
const $ = (id) => document.getElementById(id);
const esc = (value) => String(value ?? "—").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pct = (value) => value == null ? "—" : `${(Number(value) * 100).toFixed(2)}%`;
const num = (value) => value == null ? "—" : Number(value).toFixed(2);
const money = (value, suffix="") => value == null ? "—" : `${new Intl.NumberFormat("en-US", {style:"currency", currency:"USD"}).format(Number(value))}${suffix}`;
const badge = (value) => `<span class="badge ${value === "pass" ? "pass" : value === "fail" ? "fail" : ""}">${esc(value)}</span>`;
async function get(path) { const response = await fetch(`${api}${path}`); if (!response.ok) throw new Error(response.status === 404 ? "Experiment not found" : `API request failed (${response.status})`); return response.json(); }
async function send(path, method, body) { const response = await fetch(`${api}${path}`, {method, headers:{"Content-Type":"application/json"}, body:body == null ? undefined : JSON.stringify(body)}); const value=await response.json(); if(!response.ok) throw new Error(value.detail||`API request failed (${response.status})`); return value; }
function showError(error) { $("error").textContent = error.message; $("error").classList.remove("hidden"); }
function metricValue(key, value) { if (value == null) return "—"; if (["total_return","cagr","max_drawdown","volatility","win_rate"].includes(key)) return pct(value); if (key === "expectancy") return money(value, " / trade"); return num(value); }
function metricGrid(metrics) { if (!metrics) return `<div class="empty">No metrics recorded</div>`; return `<div class="metrics">${Object.entries(metrics).filter(([,v]) => v != null).map(([k,v]) => `<div class="metric"><span>${esc(k.replaceAll("_"," "))}</span><strong>${metricValue(k,v)}</strong></div>`).join("")}</div>`; }
function metricComparison(strategy, benchmark) { const keys=["total_return","cagr","max_drawdown","volatility","sharpe","sortino","calmar"]; return `<table><thead><tr><th>Metric</th><th>Strategy</th><th>Buy & Hold</th></tr></thead><tbody>${keys.map(k=>`<tr><td>${esc(k.replaceAll("_"," "))}</td><td>${metricValue(k,strategy?.[k])}</td><td>${metricValue(k,benchmark?.[k])}</td></tr>`).join("")}</tbody></table>`; }
async function loadOverview() {
  const [summary, experiments, knowledge, paper, datasets] = await Promise.all([get("/operator-summary"), get("/experiments?limit=50"), get("/knowledge?limit=20"), get("/paper/sessions"), get("/datasets?limit=50")]);
  const cards = [["Active experiments",summary.active_experiments],["Completed",summary.completed_experiments],["Rejected hypotheses",summary.rejected_hypotheses],["Eligible for paper",summary.eligible_for_paper],["Failed gates",summary.failed_gates],["High findings",summary.high_findings],["Warnings",summary.warning_findings]];
  $("summary").innerHTML = cards.map(([label,value]) => `<div class="card"><span class="eyebrow">${esc(label)}</span><strong>${esc(value)}</strong></div>`).join("");
  $("experiments").innerHTML = experiments.items.length ? `<table><thead><tr><th>Experiment</th><th>Status</th><th>Latest run</th><th>Coverage</th><th>Gate</th></tr></thead><tbody>${experiments.items.map(x => `<tr><td><a href="?experiment=${x.experiment_id}">${esc(x.experiment_id)}</a></td><td>${badge(x.status)}</td><td>${esc(x.latest_run_status)}</td><td><div class="coverage">${x.validation_coverage.map(badge).join("") || "—"}</div></td><td>${x.latest_gate_decision ? badge(x.latest_gate_decision) : "—"}</td></tr>`).join("")}</tbody></table>` : `<div class="empty">No experiments yet.</div>`;
  $("knowledge-list").innerHTML = knowledge.items.length ? `<table><thead><tr><th>Hypothesis</th><th>Status</th><th>Domain</th><th>Summary / rejection</th><th>Reconsider if</th></tr></thead><tbody>${knowledge.items.map(x => `<tr><td>${esc(x.hypothesis_id)}</td><td>${badge(x.status)}</td><td>${esc(x.signature.instrument)} · ${esc(x.signature.timeframe)}<br><span class="muted">${esc(x.signature.market)}</span></td><td>${esc(x.rejection_reason || x.summary)}</td><td>${x.reconsideration_conditions.map(esc).join(", ") || "—"}</td></tr>`).join("")}</tbody></table>` : `<div class="empty">No research-memory records yet.</div>`;
  $("paper-sessions").innerHTML = paper.length ? `<table><thead><tr><th>Session</th><th>Feed</th><th>Status</th><th>Participants</th><th>Last observation</th></tr></thead><tbody>${paper.map(x => `<tr><td><a href="?paper_session=${x.id}">${esc(x.instrument)} · ${esc(x.timeframe)}</a><br><span class="muted">${esc(x.id)}</span></td><td>${esc(x.provider_name)} / ${esc(x.provider_version)}</td><td>${badge(x.status)}</td><td>${esc(x.participant_count)}</td><td>${esc(x.last_processed_at)}</td></tr>`).join("")}</tbody></table>` : `<div class="empty">No paper sessions. Passing historical validation does not start paper trading automatically.</div>`;
  $("datasets").innerHTML = datasets.items.length ? `<table><thead><tr><th>Snapshot</th><th>Provider/feed</th><th>Asset</th><th>Requested range</th><th>Actual range / bars</th><th>Checksum</th></tr></thead><tbody>${datasets.items.map(x=>`<tr><td><a href="?dataset=${x.id}">${esc(x.id)}</a></td><td>${esc(x.provider)} / ${esc(x.feed)}</td><td>${esc(x.instrument)} · ${esc(x.timeframe)}</td><td>${esc(x.requested_start_at)}<br>${esc(x.requested_end_at)}</td><td>${esc(x.actual_start_at)}<br>${esc(x.actual_end_at)} · ${esc(x.bar_count)} bars</td><td class="muted">${esc(x.checksum)}</td></tr>`).join("")}</tbody></table>` : `<div class="empty">No immutable datasets yet.</div>`;
  $("research-dataset").innerHTML = datasets.items.map(x => `<option value="${esc(x.id)}">${esc(x.instrument)} · ${esc(x.timeframe)} · ${esc(x.id)}</option>`).join("");
  $("updated").textContent = `Loaded ${new Date().toLocaleTimeString()}`;
}
async function loadPaperSession(id) {
  $("overview").classList.add("hidden"); $("experiment-detail").classList.remove("hidden");
  const detail = await get(`/paper/sessions/${id}`); const s = detail.session;
  const rows = detail.participants.map(p => `<tr><td><a href="#participant-${p.id}">${esc(p.strategy_version_id)}</a></td><td>${badge(p.status)}</td><td>${pct(p.metrics?.total_return)}</td><td>${pct(p.metrics?.max_drawdown)}</td><td>${num(p.metrics?.sharpe)}</td><td>${esc(p.metrics?.trade_count)}</td><td>${esc(p.processed_bars)}</td></tr>`).join("");
  const participants = detail.participants.map(p => `<div id="participant-${p.id}" class="panel"><div class="section-heading"><div><span class="eyebrow">PAPER PARTICIPANT</span><h2>${esc(p.strategy_version_id)}</h2></div>${badge(p.status)}</div><p>Admission gate ${esc(p.source_gate_evaluation_id)} · ${esc(p.paper_engine_version)}</p><p>Fake capital ${esc(p.initial_capital)} · cash ${esc(p.current_cash)} · equity ${esc(p.current_equity)}</p><p class="muted">Started ${esc(p.started_at)} · observed bars ${esc(p.processed_bars)}</p>${metricGrid(p.metrics)}<h3>Position</h3><pre>${esc(JSON.stringify(p.open_position ?? null,null,2))}</pre><h3>Latest signal / simulated fill</h3><pre>${esc(JSON.stringify({signal:p.latest_signal,fill:p.latest_fill},null,2))}</pre></div>`).join("");
  $("experiment-detail").innerHTML = `<a href="/dashboard/#paper-arena">← Paper Arena</a><div class="section-heading"><div><span class="eyebrow">PAPER ARENA</span><h1>${esc(s.instrument)} / ${esc(s.timeframe)}</h1></div>${badge(s.status)}</div><div class="panel"><h2>Forward feed</h2><p>${esc(s.provider_name)} / ${esc(s.provider_version)}</p><p class="muted">Evaluation starts ${esc(s.evaluation_start)} · last observation ${esc(s.last_processed_at)} · dataset checksum ${esc(s.dataset_checksum)}</p></div><div class="panel"><h2>Participant comparison</h2>${rows ? `<table><thead><tr><th>Strategy version</th><th>Status</th><th>Return</th><th>Max DD</th><th>Sharpe</th><th>Trades</th><th>Bars</th></tr></thead><tbody>${rows}</tbody></table>` : `<div class="empty">No admitted participants.</div>`}<p class="muted">Comparable evidence only; the Paper Arena does not select a winner.</p></div>${participants}`;
}
async function loadExperiment(id) {
  $("overview").classList.add("hidden"); $("experiment-detail").classList.remove("hidden");
  const detail = await get(`/experiments/${id}`); const runs = detail.runs; const run = runs.at(-1);
  let validations = [], gates = []; if (run) [validations, gates] = await Promise.all([get(`/experiment-runs/${run.id}/validations`), get(`/experiment-runs/${run.id}/gate-evaluations`)]);
  const byType = Object.fromEntries(validations.map(v => [v.validation_type,v])); const adversarial = byType.adversarial_review; const gateValue = gates.at(-1);
  const sections = validations.filter(v => !["adversarial_review","backtest"].includes(v.validation_type)).map(v => `<div class="panel"><div class="section-heading"><h2>${esc(v.validation_type.replaceAll("_"," "))}</h2>${badge(v.status)}</div>${metricGrid(v.metrics)}${renderEvidence(v)}</div>`).join("");
  const backtest=byType.backtest, benchmark=backtest?.evidence?.benchmark_metrics; const chartAction=run&&backtest&&run.status==="completed"&&backtest.status==="passed"?`<a class="button-link" href="?experiment=${id}&view=backtest&run=${run.id}">View backtest chart</a>`:"";
  $("experiment-detail").innerHTML = `<a href="/dashboard/">← All experiments</a><div class="section-heading"><div><span class="eyebrow">EXPERIMENT</span><h1>${esc(id)}</h1></div>${badge(detail.experiment.status)}</div><div class="panel"><h2>Hypothesis</h2><h3>${esc(detail.hypothesis.title)}</h3><p>${esc(detail.hypothesis.description)}</p></div><div class="panel"><h2>Strategy</h2><p>${esc(detail.strategy.name)} · ${esc(detail.strategy_version.algorithm_key)} / ${esc(detail.strategy_version.version)}</p><pre>${esc(JSON.stringify(detail.strategy_version.parameters,null,2))}</pre></div><div class="panel"><div class="section-heading"><h2>Dataset & lineage</h2><a href="?dataset=${detail.dataset_snapshot.id}">Inspect dataset quality</a></div><p>${esc(detail.dataset_snapshot.instrument)} · ${esc(detail.dataset_snapshot.timeframe)} · ${esc(detail.dataset_snapshot.market)}</p><p><strong>Requested:</strong> ${esc(detail.dataset_snapshot.requested_start_at)} → ${esc(detail.dataset_snapshot.requested_end_at)}<br><strong>Actual:</strong> ${esc(detail.dataset_snapshot.actual_start_at)} → ${esc(detail.dataset_snapshot.actual_end_at)} · ${esc(detail.dataset_snapshot.bar_count)} bars</p><p class="muted">Checksum ${esc(detail.dataset_snapshot.checksum)}</p>${run ? `<p>Engine ${esc(run.engine_version)} · Fees ${esc(run.fee_model_version)} · Slippage ${esc(run.slippage_model_version)}</p>${chartAction}` : `<div class="empty">No experiment run yet.</div>`}</div><div class="panel"><h2>Validation coverage</h2><div class="coverage">${["backtest","out_of_sample","walk_forward","parameter_sensitivity","stress","monte_carlo","adversarial_review"].map(x => byType[x] ? badge(`${x} ✓`) : badge(`${x} NOT_RUN`)).join("")}${gateValue?badge(`gate ${gateValue.decision}`):badge("gate NOT_RUN")}</div></div>${run?validationControls(run.id,detail,byType):""}${backtest?`<div class="panel"><div class="section-heading"><div><h2>BACKTEST</h2><span class="muted">Deterministic execution completed; this is not research-gate approval.</span></div>${badge("completed")}</div>${metricComparison(backtest.metrics,benchmark)}${metricGrid({profit_factor:backtest.metrics?.profit_factor,win_rate:backtest.metrics?.win_rate,expectancy:backtest.metrics?.expectancy,trade_count:backtest.metrics?.trade_count})}</div>`:""}${sections}${renderAdversarial(adversarial)}${renderGate(gateValue)}`;
  document.querySelectorAll(".validation-form").forEach(form=>form.addEventListener("submit",async event=>{event.preventDefault();try{const payload=JSON.parse(form.elements.configuration.value);const result=await send(`/experiment-runs/${run.id}/${form.dataset.path}`,"POST",payload);form.querySelector("pre").textContent=JSON.stringify(result,null,2);form.querySelector("pre").classList.remove("hidden");}catch(error){showError(error);}}));
  document.querySelectorAll(".copy-validation-curl").forEach(button=>button.addEventListener("click",async()=>{const form=button.closest("form");const command=`curl -X POST "http://127.0.0.1:8000/api/v1/experiment-runs/${run.id}/${form.dataset.path}" -H 'Content-Type: application/json' --data '${form.elements.configuration.value}'`;await navigator.clipboard?.writeText(command);form.querySelector("pre").textContent=command;form.querySelector("pre").classList.remove("hidden");}));
}

function validationControls(runId,detail,byType) { const ids=Object.fromEntries(Object.entries(byType).map(([k,v])=>[k,v.id])); const configurations={"validations/out-of-sample":{training_start:detail.dataset_snapshot.actual_start_at,training_end:"2023-12-31T23:59:59Z",test_start:"2024-01-01T00:00:00Z",test_end:detail.dataset_snapshot.actual_end_at},"validations/walk-forward":{mode:"expanding",training_window:504,test_window:126,step:126},"validations/parameter-sensitivity":{parameters:{short_window:[40,50,60],long_window:[180,200,220]},maximum_combinations:9},"validations/stress":{scenarios:[{id:"fees-2x",name:"Double fees",stress_type:"fee_multiplier",configuration:{multiplier:"2"}},{id:"delay-1",name:"One additional bar delay",stress_type:"execution_delay",configuration:{additional_delay_bars:1}}]},"validations/monte-carlo":{simulation_count:1000,random_seed:20260831,confidence_percentiles:[0.05,0.5,0.95],sampling_method:"trade_bootstrap",drawdown_threshold:-0.25,ruin_equity_fraction:0.5},"validations/adversarial-review":{max_oos_sharpe_drop:0.5,max_oos_return_drop:0.2,max_oos_drawdown_worsening:0.1,min_profitable_fold_ratio:0.6,max_fold_return_dispersion:0.2,max_fold_sharpe_dispersion:1,max_neighbor_sharpe_delta:0.5,min_profitable_parameter_ratio:0.6,max_parameter_sharpe_dispersion:1,max_stress_return_drop:0.2,max_stress_drawdown_worsening:0.1,max_bootstrap_loss_frequency:0.3,max_adverse_bootstrap_drawdown:-0.25,max_bootstrap_losing_streak:4,max_historical_return_percentile:0.95,min_trade_count_for_interpretation:20,max_top_trade_profit_share:0.5,max_top_three_profit_share:0.8},"gate-evaluations":{policy_id:"HISTORICAL_TO_PAPER",policy_version:1,policy_name:"Explicit historical research gate",required_validations:["backtest","out_of_sample","walk_forward","parameter_sensitivity","stress","monte_carlo"],require_adversarial_report:true,rules:[],evidence_ids:ids}}; return `<div class="panel"><h2>Research execution controls</h2><p class="muted">Execution completion records evidence; only the explicit gate can decide policy eligibility.</p>${Object.entries(configurations).map(([path,value])=>`<form class="validation-form" data-path="${esc(path)}"><h3>${esc(path.split("/").at(-1).replaceAll("-"," "))}</h3><label>Versioned explicit configuration<textarea name="configuration" rows="8">${esc(JSON.stringify(value,null,2))}</textarea></label><button type="submit">Run</button> <button type="button" class="secondary copy-validation-curl">Copy curl</button><pre class="result hidden"></pre></form>`).join("")}</div>`; }

function qualityPanel(q) { const failed=q.has_structural_errors; return `<div class="panel ${failed?"quality-warning":""}"><div class="section-heading"><h2>Dataset quality</h2>${failed?badge("STRUCTURAL FAILURE"):badge("STRUCTURALLY VALID · COMPLETENESS UNVERIFIED")}</div>${failed?`<div class="error">Research evidence from this dataset is structurally invalid and must not advance.</div>`:""}<div class="metrics"><div class="metric"><span>Actual coverage</span><strong>${esc(q.actual_start_at)} → ${esc(q.actual_end_at)}</strong></div><div class="metric"><span>Bars</span><strong>${esc(q.total_bars)}</strong></div><div class="metric"><span>Duplicates</span><strong>${esc(q.duplicate_timestamps)}</strong></div><div class="metric"><span>Ordering</span><strong>${q.ordering_valid?"Valid":"Invalid"}</strong></div><div class="metric"><span>OHLCV integrity</span><strong>${q.ohlcv_integrity_valid?"Valid":"Invalid"}</strong></div></div><h3>Observed bars by calendar year</h3><div class="year-bars">${Object.entries(q.bars_by_calendar_year).map(([y,n])=>`<span>${esc(y)}: ${esc(n)}</span>`).join("")}</div>${failed?`<pre>${esc(JSON.stringify({ordering:q.ordering_failure_examples,ohlcv:q.ohlcv_failure_examples},null,2))}</pre>`:""}<p class="muted">${esc(q.completeness_note)}</p></div>`; }
async function loadDataset(id) { $("overview").classList.add("hidden"); $("experiment-detail").classList.remove("hidden"); const [d,q]=await Promise.all([get(`/datasets/${id}`),get(`/datasets/${id}/quality`)]); $("experiment-detail").innerHTML=`<a href="/dashboard/#market-data">← Market Data</a><div class="section-heading"><div><span class="eyebrow">DATASET SNAPSHOT</span><h1>${esc(d.instrument)} / ${esc(d.timeframe)}</h1></div></div><div class="panel"><h2>Immutable lineage</h2><p><strong>Requested:</strong> ${esc(d.requested_start_at)} → ${esc(d.requested_end_at)}<br><strong>Actual:</strong> ${esc(d.actual_start_at)} → ${esc(d.actual_end_at)}<br><strong>Bars:</strong> ${esc(d.bar_count)}</p><p class="muted">${esc(d.id)} · ${esc(d.checksum)}</p></div>${qualityPanel(q)}`; }

function chartTime(value) { return Math.floor(new Date(value).getTime()/1000); }
function makeChart(element, height) { return LightweightCharts.createChart(element,{height,layout:{background:{color:"#fffdf7"},textColor:"#18211d"},grid:{vertLines:{color:"#eee9dd"},horzLines:{color:"#eee9dd"}},crosshair:{mode:LightweightCharts.CrosshairMode.Normal},timeScale:{timeVisible:true,borderColor:"#d8d2c3"},rightPriceScale:{borderColor:"#d8d2c3"}}); }
async function loadBacktest(experimentId,runId) { $("overview").classList.add("hidden"); $("experiment-detail").classList.remove("hidden"); const v=await get(`/experiment-runs/${runId}/backtest-visualization`); const q=v.quality; const execution=v.execution; $("experiment-detail").innerHTML=`<a href="?experiment=${experimentId}">← Experiment summary</a><div class="section-heading"><div><span class="eyebrow">BACKTEST EVIDENCE</span><h1>${esc(v.instrument)} / ${esc(v.timeframe)}</h1><p>${esc(v.strategy)} · ${esc(v.indicator_labels.short)} / ${esc(v.indicator_labels.long)}</p></div>${badge("read only")}</div><div class="panel compact"><div class="metrics"><div class="metric"><span>ExperimentRun</span><strong>${esc(v.run_id)}</strong></div><div class="metric"><span>DatasetSnapshot</span><strong>${esc(v.dataset_snapshot_id)}</strong></div><div class="metric"><span>Actual range / bars</span><strong>${esc(v.actual_start_at)} → ${esc(v.actual_end_at)} · ${esc(v.bar_count)}</strong></div><div class="metric"><span>Initial cash / fraction</span><strong>${money(execution.backtest.initial_cash)} · ${esc(execution.backtest.position_fraction)}</strong></div><div class="metric"><span>Fees / slippage</span><strong>${esc(execution.fee.version)} · ${esc(execution.slippage.version)}</strong></div><div class="metric"><span>Fingerprint</span><strong>${esc(v.result_fingerprint)}</strong></div></div></div><div class="panel"><div class="chart-legend"><span>Candles</span><span class="short">${esc(v.indicator_labels.short)}</span><span class="long">${esc(v.indicator_labels.long)}</span><span class="buy">BUY fill</span><span class="sell">SELL fill</span></div><div id="price-chart" class="chart"></div><div id="position-track" class="position-track" title="Persisted fill-derived LONG periods"></div><div id="event-detail" class="event-detail muted">Select a fill marker or trade to inspect signal-close versus execution-open timing.</div></div><div class="panel"><h2>Strategy equity vs Buy & Hold</h2><div id="equity-chart" class="chart"></div></div><div class="panel"><h2>Trades</h2><div id="trades-panel"></div></div>${qualityPanel(q)}`;
  const price=makeChart($("price-chart"),520); const candles=price.addSeries(LightweightCharts.CandlestickSeries,{upColor:"#1e5d46",downColor:"#9c3b2f",borderVisible:false,wickUpColor:"#1e5d46",wickDownColor:"#9c3b2f"}); candles.setData(v.bars.map(b=>({time:chartTime(b.timestamp),open:Number(b.open),high:Number(b.high),low:Number(b.low),close:Number(b.close)}))); const short=price.addSeries(LightweightCharts.LineSeries,{color:"#2b6cb0",lineWidth:2,title:v.indicator_labels.short}); const long=price.addSeries(LightweightCharts.LineSeries,{color:"#a96d16",lineWidth:2,title:v.indicator_labels.long}); short.setData(v.indicators.map(x=>({time:chartTime(x.timestamp),value:Number(x.short)}))); long.setData(v.indicators.map(x=>({time:chartTime(x.timestamp),value:Number(x.long)}))); const markers=v.fills.map(f=>({time:chartTime(f.timestamp),position:f.side==="buy"?"belowBar":"aboveBar",color:f.side==="buy"?"#1e5d46":"#9c3b2f",shape:f.side==="buy"?"arrowUp":"arrowDown",text:f.side.toUpperCase()})); LightweightCharts.createSeriesMarkers(candles,markers); price.timeScale().fitContent();
  const equity=makeChart($("equity-chart"),280); const strategyLine=equity.addSeries(LightweightCharts.LineSeries,{color:"#1e5d46",lineWidth:2,title:"Strategy"}); const benchmarkLine=equity.addSeries(LightweightCharts.LineSeries,{color:"#6d746f",lineWidth:2,title:"Buy & Hold"}); strategyLine.setData(v.equity.map(x=>({time:chartTime(x.timestamp),value:Number(x.equity)}))); benchmarkLine.setData(v.benchmark_equity.map(x=>({time:chartTime(x.timestamp),value:Number(x.equity)}))); equity.timeScale().fitContent(); price.timeScale().subscribeVisibleLogicalRangeChange(range=>range&&equity.timeScale().setVisibleLogicalRange(range));
  const track=$("position-track"); const first=chartTime(v.bars[0].timestamp),last=chartTime(v.bars.at(-1).timestamp),span=Math.max(1,last-first); track.innerHTML=v.positions.map(p=>`<span style="left:${(chartTime(p.start_at)-first)/span*100}%;width:${(chartTime(p.end_at)-chartTime(p.start_at))/span*100}%" title="LONG ${esc(p.start_at)} → ${esc(p.end_at)}">LONG</span>`).join("");
  const showEvent=(f,t)=>{$("event-detail").innerHTML=`<strong>${esc(f.side.toUpperCase())} execution</strong><br>Signal generated: ${esc(f.signal_timestamp)} close<br>Order eligible: ${esc(f.order_eligible_timestamp)} open<br>Fill: ${esc(f.timestamp)} at ${money(f.fill_price)} · quantity ${esc(f.quantity)} · order/fill ${esc(f.order_id)}${t?` · trade ${esc(t.id)}`:""}`;}; const rows=v.trades.map(t=>`<tr data-trade="${esc(t.id)}"><td>${esc(t.id)}</td><td>${esc(t.entry_timestamp)}<br>${money(t.entry_price)}</td><td>${esc(t.exit_timestamp)}<br>${money(t.exit_price)}</td><td>${esc(t.quantity)}</td><td>${num(Number(t.duration_seconds)/86400)} days</td><td>${money(t.realized_pnl)}</td><td>${pct(t.return)}</td><td>${esc(t.outcome)}</td></tr>`).join(""); $("trades-panel").innerHTML=rows?`<table><thead><tr><th>Trade</th><th>Entry</th><th>Exit</th><th>Quantity</th><th>Duration</th><th>Realized P&amp;L</th><th>Return</th><th>Outcome</th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty">No completed trades. Candles, signals, positions, and equity remain inspectable.</div>`; document.querySelectorAll("[data-trade]").forEach(row=>row.addEventListener("click",()=>{document.querySelectorAll("[data-trade]").forEach(x=>x.classList.remove("selected"));row.classList.add("selected");const t=v.trades.find(x=>x.id===row.dataset.trade);price.timeScale().setVisibleRange({from:chartTime(t.entry_timestamp)-86400*20,to:chartTime(t.exit_timestamp)+86400*20});showEvent(v.fills.find(f=>f.order_id===t.entry_order_id),t);})); price.subscribeClick(param=>{if(!param.time)return;const f=v.fills.find(x=>chartTime(x.timestamp)===param.time);if(f){const t=v.trades.find(x=>x.entry_order_id===f.order_id||x.exit_order_id===f.order_id);showEvent(f,t);if(t)document.querySelector(`[data-trade="${t.id}"]`)?.classList.add("selected");}}); window.addEventListener("resize",()=>{price.applyOptions({width:$("price-chart").clientWidth});equity.applyOptions({width:$("equity-chart").clientWidth});}); }
function renderEvidence(v) { const e=v.evidence||{}; if(v.validation_type==="walk_forward") return `<h3>Folds</h3><pre>${esc(JSON.stringify(e.result?.aggregate||e.aggregate||{},null,2))}</pre>`; if(v.validation_type==="parameter_sensitivity") return `<h3>Surface summary</h3><pre>${esc(JSON.stringify(e.result?.summary||e.summary||{},null,2))}</pre>`; if(v.validation_type==="stress") return `<h3>Scenario summary</h3><pre>${esc(JSON.stringify(e.result?.aggregate||e.aggregate||{},null,2))}</pre>`; if(v.validation_type==="monte_carlo") return `<h3>Empirical bootstrap distribution</h3><pre>${esc(JSON.stringify(e.result?.distribution_summary||e.distribution_summary||{},null,2))}</pre>`; const benchmark=e.benchmark_metrics||e.material_result?.benchmark_metrics; return benchmark ? `<h3>Buy & Hold benchmark</h3>${metricGrid(benchmark)}` : ""; }
function renderAdversarial(v) { if(!v) return `<div class="panel"><h2>Adversarial findings</h2><div class="empty">No adversarial report.</div></div>`; const report=v.evidence.report||{}; const findings=report.findings||[]; return `<div class="panel"><h2>Adversarial findings</h2>${findings.length ? findings.map(f=>`<div class="finding"><span class="badge ${esc(f.severity)}">${esc(f.severity)}</span><h3>${esc(f.code)}</h3><p>${esc(f.title)}</p><pre>${esc(JSON.stringify(f.evidence,null,2))}</pre></div>`).join("") : `<div class="empty">No findings recorded.</div>`}</div>`; }
function renderGate(g) { if(!g) return `<div class="panel"><h2>Validation gate</h2><div class="empty">No gate evaluation.</div></div>`; return `<div class="panel"><div class="section-heading"><div><h2>Validation gate</h2><span>${esc(g.policy_id)} v${esc(g.policy_version)}</span></div>${badge(g.decision)}</div>${g.rule_results.map(r=>`<div class="finding"><strong>${r.result==="pass"?"✓":"✗"} ${esc(r.rule_code)}</strong><div class="muted">actual ${esc(r.actual)} · expected ${esc(r.expected)}</div></div>`).join("")}<p class="muted">${esc(g.decision_semantics)}</p></div>`; }
function importPayload(form) { const data=new FormData(form); return {provider:"ALPACA",instrument:data.get("instrument"),market:"US_EQUITIES",timeframe:data.get("timeframe"),start:`${data.get("start")}:00Z`,end:`${data.get("end")}:00Z`,feed:data.get("feed"),adjustment_policy:"raw"}; }
$("dataset-import-form").addEventListener("submit", async event => { event.preventDefault(); try { const result=await send("/market-data/import","POST",importPayload(event.target)); $("dataset-import-result").textContent=JSON.stringify(result,null,2); $("dataset-import-result").classList.remove("hidden"); await loadOverview(); } catch(error) { showError(error); } });
$("show-import-curl").addEventListener("click", async () => { const payload=importPayload($("dataset-import-form")); const command=`QUANT_LAB_URL=http://127.0.0.1:8000\n\ncurl -X POST "$QUANT_LAB_URL/api/v1/market-data/import" \\\n  -H 'Content-Type: application/json' \\\n  --data '${JSON.stringify(payload)}'`; $("dataset-import-result").textContent=command; $("dataset-import-result").classList.remove("hidden"); await navigator.clipboard?.writeText(command); });
async function loadAlpacaPaper() { const [account,positions,orders]=await Promise.all([get("/brokers/alpaca/paper/account"),get("/brokers/alpaca/paper/positions"),get("/brokers/alpaca/paper/orders?status=all")]); $("alpaca-account").innerHTML=`<div class="metrics"><div class="metric"><span>SIMULATED ACCOUNT</span><strong>${esc(account.status)}</strong></div><div class="metric"><span>Cash</span><strong>${esc(account.cash)} ${esc(account.currency)}</strong></div><div class="metric"><span>Equity</span><strong>${esc(account.equity)}</strong></div><div class="metric"><span>Buying power</span><strong>${esc(account.buying_power)}</strong></div></div>`; $("alpaca-positions").innerHTML=`<h3>PAPER positions</h3>${positions.length?`<table><thead><tr><th>Symbol</th><th>Qty</th><th>Entry</th><th>Value</th><th>Unrealized P&amp;L</th><th></th></tr></thead><tbody>${positions.map(x=>`<tr><td>${esc(x.symbol)}</td><td>${esc(x.quantity)}</td><td>${esc(x.average_entry_price)}</td><td>${esc(x.market_value)}</td><td>${esc(x.unrealized_pnl)}</td><td><button class="close-paper-position" data-symbol="${esc(x.symbol)}">Close PAPER</button></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No paper positions.</div>`}`; $("alpaca-orders").innerHTML=`<h3>Recent PAPER orders</h3>${orders.length?`<table><thead><tr><th>ID</th><th>Symbol</th><th>Side</th><th>Qty</th><th>Status</th></tr></thead><tbody>${orders.map(x=>`<tr><td>${esc(x.order_id)}</td><td>${esc(x.symbol)}</td><td>${esc(x.side)}</td><td>${esc(x.quantity)}</td><td>${badge(x.status)}</td></tr>`).join("")}</tbody></table>`:`<div class="empty">No paper orders.</div>`}`; document.querySelectorAll(".close-paper-position").forEach(button=>button.addEventListener("click",async()=>{if(!confirm(`Close the simulated PAPER position for ${button.dataset.symbol}?`))return;try{await send(`/brokers/alpaca/paper/positions/${encodeURIComponent(button.dataset.symbol)}?confirm=true`,"DELETE");await loadAlpacaPaper();}catch(error){showError(error);}})); }
$("refresh-alpaca").addEventListener("click",()=>loadAlpacaPaper().catch(showError));
$("alpaca-order-form").elements.client_order_id.value=`quant-lab-${Date.now()}`;
$("alpaca-order-form").addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.target);if(!confirm("Submit this simulated Alpaca PAPER order?"))return;try{const result=await send("/brokers/alpaca/paper/orders","POST",{symbol:data.get("symbol"),side:data.get("side"),quantity:data.get("quantity"),type:"market",time_in_force:"day",client_order_id:data.get("client_order_id")});$("alpaca-order-result").textContent=JSON.stringify(result,null,2);$("alpaca-order-result").classList.remove("hidden");await loadAlpacaPaper();}catch(error){showError(error);}});
$("prior-art-form").addEventListener("submit", async event => { event.preventDefault(); const data=new FormData(event.target); try { const response=await fetch(`${api}/knowledge/prior-art-check`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({strategy_family:data.get("strategy_family"),market:data.get("market"),instrument:data.get("instrument"),timeframe:data.get("timeframe"),parameters:JSON.parse(data.get("parameters")),numeric_parameter_relative_tolerance:Number(data.get("tolerance"))})}); const result=await response.json(); if(!response.ok) throw new Error(result.detail||"Prior-art request failed"); $("prior-art-result").textContent=JSON.stringify(result,null,2); $("prior-art-result").classList.remove("hidden"); } catch(error) { showError(error); } });
function hypothesisPayload(form) { const data=new FormData(form); return {title:data.get("title"),description:data.get("description"),rationale:data.get("rationale"),strategy_family:"moving_average_trend",market:"US_EQUITIES",instrument:"SPY",timeframe:"1Day",parameters:{short_window:50,long_window:200},expected_benefit:"Transparent trend participation",expected_tradeoff:"Whipsaw and delayed entries",success_criteria:"Reproducible validation evidence",rejection_criteria:"Insufficient robust evidence",numeric_parameter_relative_tolerance:0.02}; }
function strategyPayload(form) { const data=new FormData(form); return {name:"SPY MA Trend",description:"Moving-average trend strategy",strategy_family:"moving_average_trend",version:"v1",git_commit:data.get("git_commit"),algorithm_key:data.get("algorithm_key"),parameters:{short_window:Number(data.get("short_window")),long_window:Number(data.get("long_window"))}}; }
function experimentPayload(form) { const data=new FormData(form); return {hypothesis_id:data.get("hypothesis_id"),strategy_version_id:data.get("strategy_version_id"),dataset_snapshot_id:data.get("dataset_snapshot_id")}; }
function runPayload(form) { const data=new FormData(form); return {initial_cash:data.get("initial_cash"),position_fraction:"1",fee:{model:"percentage",rate:data.get("fee_rate")},slippage:{model:"basis_points",basis_points:data.get("slippage_bps")},periods_per_year:252,annual_risk_free_rate:"0"}; }
function showResearch(value) { $("research-result").textContent=typeof value==="string"?value:JSON.stringify(value,null,2); $("research-result").classList.remove("hidden"); }
$("hypothesis-create-form").addEventListener("submit",async event=>{event.preventDefault();try{const result=await send("/hypotheses","POST",hypothesisPayload(event.target));$("research-hypothesis-id").value=result.id;showResearch(result);}catch(error){showError(error);}});
$("strategy-create-form").addEventListener("submit",async event=>{event.preventDefault();try{const result=await send("/strategy-versions","POST",strategyPayload(event.target));$("research-version-id").value=result.strategy_version_id;showResearch(result);}catch(error){showError(error);}});
$("experiment-create-form").addEventListener("submit",async event=>{event.preventDefault();try{const result=await send("/experiments","POST",experimentPayload(event.target));$("research-experiment-id").value=result.experiment_id;showResearch(result);await loadOverview();}catch(error){showError(error);}});
$("experiment-run-form").addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.target);try{const result=await send(`/experiments/${data.get("experiment_id")}/runs`,"POST",runPayload(event.target));showResearch(result);location.href=`?experiment=${result.experiment_id}`;}catch(error){showError(error);}});
document.querySelectorAll(".copy-research-curl").forEach(button=>button.addEventListener("click",async()=>{let path,payload;if(button.dataset.action==="hypothesis"){path="hypotheses";payload=hypothesisPayload($("hypothesis-create-form"));}else if(button.dataset.action==="strategy"){path="strategy-versions";payload=strategyPayload($("strategy-create-form"));}else if(button.dataset.action==="experiment"){path="experiments";payload=experimentPayload($("experiment-create-form"));}else{const form=$("experiment-run-form");path=`experiments/${new FormData(form).get("experiment_id")}/runs`;payload=runPayload(form);}const command=`curl -X POST "http://127.0.0.1:8000/api/v1/${path}" \\\n  -H 'Content-Type: application/json' \\\n  --data '${JSON.stringify(payload)}'`;showResearch(command);await navigator.clipboard?.writeText(command);}));
(async () => { try { const end=new Date(); end.setMinutes(end.getMinutes()-end.getTimezoneOffset()); $("dataset-import-form").elements.end.value=end.toISOString().slice(0,16); const params=new URLSearchParams(location.search); const experiment=params.get("experiment"), view=params.get("view"), run=params.get("run"), dataset=params.get("dataset"), paper=params.get("paper_session"); paper ? await loadPaperSession(paper) : dataset ? await loadDataset(dataset) : experiment&&view==="backtest"&&run ? await loadBacktest(experiment,run) : experiment ? await loadExperiment(experiment) : await loadOverview(); } catch(error) { showError(error); } })();
