const api = "/api/v1";
const $ = (id) => document.getElementById(id);
const esc = (value) => String(value ?? "—").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pct = (value) => value == null ? "—" : `${(Number(value) * 100).toFixed(2)}%`;
const num = (value) => value == null ? "—" : Number(value).toFixed(2);
const badge = (value) => `<span class="badge ${value === "pass" ? "pass" : value === "fail" ? "fail" : ""}">${esc(value)}</span>`;
async function get(path) { const response = await fetch(`${api}${path}`); if (!response.ok) throw new Error(response.status === 404 ? "Experiment not found" : `API request failed (${response.status})`); return response.json(); }
function showError(error) { $("error").textContent = error.message; $("error").classList.remove("hidden"); }
function metricGrid(metrics) { if (!metrics) return `<div class="empty">No metrics recorded</div>`; const percentage = new Set(["total_return","cagr","max_drawdown","volatility","win_rate","expectancy"]); return `<div class="metrics">${Object.entries(metrics).filter(([,v]) => v != null).map(([k,v]) => `<div class="metric"><span>${esc(k.replaceAll("_"," "))}</span><strong>${percentage.has(k) ? pct(v) : esc(v)}</strong></div>`).join("")}</div>`; }
async function loadOverview() {
  const [summary, experiments, knowledge, paper] = await Promise.all([get("/operator-summary"), get("/experiments?limit=50"), get("/knowledge?limit=20"), get("/paper/sessions")]);
  const cards = [["Active experiments",summary.active_experiments],["Completed",summary.completed_experiments],["Rejected hypotheses",summary.rejected_hypotheses],["Eligible for paper",summary.eligible_for_paper],["Failed gates",summary.failed_gates],["High findings",summary.high_findings],["Warnings",summary.warning_findings]];
  $("summary").innerHTML = cards.map(([label,value]) => `<div class="card"><span class="eyebrow">${esc(label)}</span><strong>${esc(value)}</strong></div>`).join("");
  $("experiments").innerHTML = experiments.items.length ? `<table><thead><tr><th>Experiment</th><th>Status</th><th>Latest run</th><th>Coverage</th><th>Gate</th></tr></thead><tbody>${experiments.items.map(x => `<tr><td><a href="?experiment=${x.experiment_id}">${esc(x.experiment_id)}</a></td><td>${badge(x.status)}</td><td>${esc(x.latest_run_status)}</td><td><div class="coverage">${x.validation_coverage.map(badge).join("") || "—"}</div></td><td>${x.latest_gate_decision ? badge(x.latest_gate_decision) : "—"}</td></tr>`).join("")}</tbody></table>` : `<div class="empty">No experiments yet.</div>`;
  $("knowledge-list").innerHTML = knowledge.items.length ? `<table><thead><tr><th>Hypothesis</th><th>Status</th><th>Domain</th><th>Summary / rejection</th><th>Reconsider if</th></tr></thead><tbody>${knowledge.items.map(x => `<tr><td>${esc(x.hypothesis_id)}</td><td>${badge(x.status)}</td><td>${esc(x.signature.instrument)} · ${esc(x.signature.timeframe)}<br><span class="muted">${esc(x.signature.market)}</span></td><td>${esc(x.rejection_reason || x.summary)}</td><td>${x.reconsideration_conditions.map(esc).join(", ") || "—"}</td></tr>`).join("")}</tbody></table>` : `<div class="empty">No research-memory records yet.</div>`;
  $("paper-sessions").innerHTML = paper.length ? `<table><thead><tr><th>Session</th><th>Feed</th><th>Status</th><th>Participants</th><th>Last observation</th></tr></thead><tbody>${paper.map(x => `<tr><td><a href="?paper_session=${x.id}">${esc(x.instrument)} · ${esc(x.timeframe)}</a><br><span class="muted">${esc(x.id)}</span></td><td>${esc(x.provider_name)} / ${esc(x.provider_version)}</td><td>${badge(x.status)}</td><td>${esc(x.participant_count)}</td><td>${esc(x.last_processed_at)}</td></tr>`).join("")}</tbody></table>` : `<div class="empty">No paper sessions. Passing historical validation does not start paper trading automatically.</div>`;
  $("updated").textContent = `Loaded ${new Date().toLocaleTimeString()}`;
}
async function loadPaperSession(id) {
  $("overview").classList.add("hidden"); $("experiment-detail").classList.remove("hidden");
  const detail = await get(`/paper/sessions/${id}`); const s = detail.session;
  const rows = detail.participants.map(p => `<tr><td><a href="#participant-${p.id}">${esc(p.strategy_version_id)}</a></td><td>${badge(p.status)}</td><td>${pct(p.metrics?.total_return)}</td><td>${pct(p.metrics?.max_drawdown)}</td><td>${num(p.metrics?.sharpe)}</td><td>${esc(p.metrics?.trade_count)}</td><td>${esc(p.processed_bars)}</td></tr>`).join("");
  const participants = detail.participants.map(p => `<div id="participant-${p.id}" class="panel"><div class="section-heading"><div><span class="eyebrow">PAPER PARTICIPANT</span><h2>${esc(p.strategy_version_id)}</h2></div>${badge(p.status)}</div><p>Admission gate ${esc(p.source_gate_evaluation_id)} · ${esc(p.paper_engine_version)}</p><p>Fake capital ${esc(p.initial_capital)} · cash ${esc(p.current_cash)} · equity ${esc(p.current_equity)}</p><p class="muted">Started ${esc(p.started_at)} · observed bars ${esc(p.processed_bars)}</p>${metricGrid(p.metrics)}<h3>Position</h3><pre>${esc(JSON.stringify(p.open_position ?? null,null,2))}</pre><h3>Latest signal / simulated fill</h3><pre>${esc(JSON.stringify({signal:p.latest_signal,fill:p.latest_fill},null,2))}</pre></div>`).join("");
  $("experiment-detail").innerHTML = `<a href="/dashboard/#paper-arena">← Paper Arena</a><div class="section-heading"><div><span class="eyebrow">PAPER ARENA</span><h1>${esc(s.instrument)} / ${esc(s.timeframe)}</h1></div>${badge(s.status)}</div><div class="panel"><h2>Forward feed</h2><p>${esc(s.provider_name)} / ${esc(s.provider_version)}</p><p class="muted">Evaluation starts ${esc(s.evaluation_start)} · last observation ${esc(s.last_processed_at)} · dataset checksum ${esc(s.dataset_checksum)}</p></div><div class="panel"><h2>Participant comparison</h2>${rows ? `<table><thead><tr><th>Strategy version</th><th>Status</th><th>Return</th><th>Max DD</th><th>Sharpe</th><th>Trades</th><th>Bars</th></tr></thead><tbody>${rows}</tbody></table>` : `<div class="empty">No admitted participants.</div>`}<p class="muted">Comparable evidence only; the Paper Arena does not select a winner.</p></div>${participants}`;
}
async function loadExperiment(id) {
  $("overview").classList.add("hidden"); $("experiment-detail").classList.remove("hidden");
  const detail = await get(`/experiments/${id}`); const runs = detail.runs; const run = runs.at(-1);
  let validations = [], gates = []; if (run) [validations, gates] = await Promise.all([get(`/experiment-runs/${run.id}/validations`), get(`/experiment-runs/${run.id}/gate-evaluations`)]);
  const byType = Object.fromEntries(validations.map(v => [v.validation_type,v])); const adversarial = byType.adversarial_review; const gateValue = gates.at(-1);
  const sections = validations.filter(v => v.validation_type !== "adversarial_review").map(v => `<div class="panel"><div class="section-heading"><h2>${esc(v.validation_type.replaceAll("_"," "))}</h2>${badge(v.status)}</div>${metricGrid(v.metrics)}${renderEvidence(v)}</div>`).join("");
  $("experiment-detail").innerHTML = `<a href="/dashboard/">← All experiments</a><div class="section-heading"><div><span class="eyebrow">EXPERIMENT</span><h1>${esc(id)}</h1></div>${badge(detail.experiment.status)}</div><div class="panel"><h2>Hypothesis</h2><h3>${esc(detail.hypothesis.title)}</h3><p>${esc(detail.hypothesis.description)}</p></div><div class="panel"><h2>Strategy</h2><p>${esc(detail.strategy.name)} · ${esc(detail.strategy_version.algorithm_key)} / ${esc(detail.strategy_version.version)}</p><pre>${esc(JSON.stringify(detail.strategy_version.parameters,null,2))}</pre></div><div class="panel"><h2>Dataset & lineage</h2><p>${esc(detail.dataset_snapshot.instrument)} · ${esc(detail.dataset_snapshot.timeframe)} · ${esc(detail.dataset_snapshot.market)}</p><p class="muted">Checksum ${esc(detail.dataset_snapshot.checksum)} · ${esc(detail.dataset_snapshot.start_at)} → ${esc(detail.dataset_snapshot.end_at)}</p>${run ? `<p>Engine ${esc(run.engine_version)} · Fees ${esc(run.fee_model_version)} · Slippage ${esc(run.slippage_model_version)}</p>` : `<div class="empty">No experiment run yet.</div>`}</div><div class="panel"><h2>Validation coverage</h2><div class="coverage">${["backtest","out_of_sample","walk_forward","parameter_sensitivity","stress","monte_carlo","adversarial_review"].map(x => byType[x] ? badge(`${x} ✓`) : badge(`${x} —`)).join("")}</div></div>${sections}${renderAdversarial(adversarial)}${renderGate(gateValue)}`;
}
function renderEvidence(v) { const e=v.evidence||{}; if(v.validation_type==="walk_forward") return `<h3>Folds</h3><pre>${esc(JSON.stringify(e.result?.aggregate||e.aggregate||{},null,2))}</pre>`; if(v.validation_type==="parameter_sensitivity") return `<h3>Surface summary</h3><pre>${esc(JSON.stringify(e.result?.summary||e.summary||{},null,2))}</pre>`; if(v.validation_type==="stress") return `<h3>Scenario summary</h3><pre>${esc(JSON.stringify(e.result?.aggregate||e.aggregate||{},null,2))}</pre>`; if(v.validation_type==="monte_carlo") return `<h3>Empirical bootstrap distribution</h3><pre>${esc(JSON.stringify(e.result?.distribution_summary||e.distribution_summary||{},null,2))}</pre>`; const benchmark=e.benchmark_metrics||e.material_result?.benchmark_metrics; return benchmark ? `<h3>Buy & Hold benchmark</h3>${metricGrid(benchmark)}` : ""; }
function renderAdversarial(v) { if(!v) return `<div class="panel"><h2>Adversarial findings</h2><div class="empty">No adversarial report.</div></div>`; const report=v.evidence.report||{}; const findings=report.findings||[]; return `<div class="panel"><h2>Adversarial findings</h2>${findings.length ? findings.map(f=>`<div class="finding"><span class="badge ${esc(f.severity)}">${esc(f.severity)}</span><h3>${esc(f.code)}</h3><p>${esc(f.title)}</p><pre>${esc(JSON.stringify(f.evidence,null,2))}</pre></div>`).join("") : `<div class="empty">No findings recorded.</div>`}</div>`; }
function renderGate(g) { if(!g) return `<div class="panel"><h2>Validation gate</h2><div class="empty">No gate evaluation.</div></div>`; return `<div class="panel"><div class="section-heading"><div><h2>Validation gate</h2><span>${esc(g.policy_id)} v${esc(g.policy_version)}</span></div>${badge(g.decision)}</div>${g.rule_results.map(r=>`<div class="finding"><strong>${r.result==="pass"?"✓":"✗"} ${esc(r.rule_code)}</strong><div class="muted">actual ${esc(r.actual)} · expected ${esc(r.expected)}</div></div>`).join("")}<p class="muted">${esc(g.decision_semantics)}</p></div>`; }
$("prior-art-form").addEventListener("submit", async event => { event.preventDefault(); const data=new FormData(event.target); try { const response=await fetch(`${api}/knowledge/prior-art-check`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({strategy_family:data.get("strategy_family"),market:data.get("market"),instrument:data.get("instrument"),timeframe:data.get("timeframe"),parameters:JSON.parse(data.get("parameters")),numeric_parameter_relative_tolerance:Number(data.get("tolerance"))})}); const result=await response.json(); if(!response.ok) throw new Error(result.detail||"Prior-art request failed"); $("prior-art-result").textContent=JSON.stringify(result,null,2); $("prior-art-result").classList.remove("hidden"); } catch(error) { showError(error); } });
(async () => { try { const params=new URLSearchParams(location.search); const experiment=params.get("experiment"); const paper=params.get("paper_session"); paper ? await loadPaperSession(paper) : experiment ? await loadExperiment(experiment) : await loadOverview(); } catch(error) { showError(error); } })();
